### ISSUE TITLE
Compilation error node 0.6.1

### ISSUE THREAD

**Issue by maerten** [nodegit/nodegit#32]
./configure:

```
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.1 
-- The C compiler identification is GNU
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5")
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/maarten/Downloads/nodegit/vendor/libgit2/build
'configure' finished successfully (1.731s)
```

Output of make:

```
[maarten@laptop: nodegit]$ make
Waf: Entering directory `/Users/maarten/Downloads/nodegit/build'
Scanning dependencies of target git2
[  2%] Building C object CMakeFiles/git2.dir/src/blob.c.o
[  4%] Building C object CMakeFiles/git2.dir/src/buffer.c.o
[  6%] Building C object CMakeFiles/git2.dir/src/cache.c.o
[  8%] Building C object CMakeFiles/git2.dir/src/commit.c.o
[ 10%] Building C object CMakeFiles/git2.dir/src/config.c.o
[ 12%] Building C object CMakeFiles/git2.dir/src/config_file.c.o
[ 14%] Building C object CMakeFiles/git2.dir/src/delta-apply.c.o
[ 17%] Building C object CMakeFiles/git2.dir/src/errors.c.o
[ 19%] Building C object CMakeFiles/git2.dir/src/fetch.c.o
[ 21%] Building C object CMakeFiles/git2.dir/src/filebuf.c.o
[ 23%] Building C object CMakeFiles/git2.dir/src/fileops.c.o
[ 25%] Building C object CMakeFiles/git2.dir/src/hash.c.o
[ 27%] Building C object CMakeFiles/git2.dir/src/hashtable.c.o
[ 29%] Building C object CMakeFiles/git2.dir/src/index.c.o
[ 31%] Building C object CMakeFiles/git2.dir/src/indexer.c.o
[ 34%] Building C object CMakeFiles/git2.dir/src/mwindow.c.o
[ 36%] Building C object CMakeFiles/git2.dir/src/netops.c.o
[ 38%] Building C object CMakeFiles/git2.dir/src/object.c.o
[ 40%] Building C object CMakeFiles/git2.dir/src/odb.c.o
[ 42%] Building C object CMakeFiles/git2.dir/src/odb_loose.c.o
[ 44%] Building C object CMakeFiles/git2.dir/src/odb_pack.c.o
[ 46%] Building C object CMakeFiles/git2.dir/src/oid.c.o
[ 48%] Building C object CMakeFiles/git2.dir/src/pack.c.o
[ 51%] Building C object CMakeFiles/git2.dir/src/path.c.o
[ 53%] Building C object CMakeFiles/git2.dir/src/pkt.c.o
[ 55%] Building C object CMakeFiles/git2.dir/src/posix.c.o
[ 57%] Building C object CMakeFiles/git2.dir/src/pqueue.c.o
[ 59%] Building C object CMakeFiles/git2.dir/src/reflog.c.o
[ 61%] Building C object CMakeFiles/git2.dir/src/refs.c.o
[ 63%] Building C object CMakeFiles/git2.dir/src/refspec.c.o
[ 65%] Building C object CMakeFiles/git2.dir/src/remote.c.o
[ 68%] Building C object CMakeFiles/git2.dir/src/repository.c.o
[ 70%] Building C object CMakeFiles/git2.dir/src/revwalk.c.o
[ 72%] Building C object CMakeFiles/git2.dir/src/sha1.c.o
[ 74%] Building C object CMakeFiles/git2.dir/src/sha1_lookup.c.o
[ 76%] Building C object CMakeFiles/git2.dir/src/signature.c.o
[ 78%] Building C object CMakeFiles/git2.dir/src/status.c.o
[ 80%] Building C object CMakeFiles/git2.dir/src/tag.c.o
[ 82%] Building C object CMakeFiles/git2.dir/src/thread-utils.c.o
[ 85%] Building C object CMakeFiles/git2.dir/src/transport.c.o
[ 87%] Building C object CMakeFiles/git2.dir/src/transport_git.c.o
[ 89%] Building C object CMakeFiles/git2.dir/src/transport_local.c.o
[ 91%] Building C object CMakeFiles/git2.dir/src/tree.c.o
[ 93%] Building C object CMakeFiles/git2.dir/src/tsort.c.o
[ 95%] Building C object CMakeFiles/git2.dir/src/util.c.o
[ 97%] Building C object CMakeFiles/git2.dir/src/vector.c.o
[100%] Building C object CMakeFiles/git2.dir/src/unix/map.c.o
Linking C shared library libgit2.dylib
[100%] Built target git2
[ 1/13] cxx: src/base.cc -> build/Release/src/base_1.o
[ 2/13] cxx: src/sig.cc -> build/Release/src/sig_1.o
../src/sig.cc:7:25: error: node_events.h: No such file or directory
../src/base.cc:7:25: error: node_events.h: No such file or directory
In file included from ../src/../include/object.h:15,
                 from ../src/../include/repo.h:15,
                 from ../src/sig.cc:11:
../src/../include/oid.h:17: error: expected class-name before ‘{’ token
In file included from ../src/../include/repo.h:15,
                 from ../src/sig.cc:11:
../src/../include/object.h:22: error: expected class-name before ‘{’ token
In file included from ../src/sig.cc:11:
../src/../include/repo.h:20: error: expected class-name before ‘{’ token
In file included from ../src/sig.cc:12:
../src/../include/sig.h:19: error: expected class-name before ‘{’ token
../src/sig.cc: In static member function ‘static v8::Handle<v8::Value> GitSig::New(const v8::Arguments&)’:
../src/sig.cc:71: error: ‘class GitSig’ has no member named ‘Wrap’
In file included from ../src/../include/object.h:15,
                 from ../src/../include/repo.h:15,
                 from ../src/../include/reference.h:15,
                 from ../src/base.cc:11:
../src/../include/oid.h:17: error: expected class-name before ‘{’ token
In file included from ../src/../include/repo.h:15,
                 from ../src/../include/reference.h:15,
                 from ../src/base.cc:11:
../src/../include/object.h:22: error: expected class-name before ‘{’ token
In file included from ../src/../include/reference.h:15,
                 from ../src/base.cc:11:
../src/../include/repo.h:20: error: expected class-name before ‘{’ token
In file included from ../src/base.cc:11:
../src/../include/reference.h:21: error: expected class-name before ‘{’ token
In file included from ../src/base.cc:12:
../src/../include/sig.h:19: error: expected class-name before ‘{’ token
In file included from ../src/../include/tree.h:16,
                 from ../src/../include/commit.h:18,
                 from ../src/base.cc:18:
../src/../include/tree_entry.h:25: error: expected class-name before ‘{’ token
In file included from ../src/../include/commit.h:18,
                 from ../src/base.cc:18:
../src/../include/tree.h:24: error: expected class-name before ‘{’ token
In file included from ../src/base.cc:18:
../src/../include/commit.h:26: error: expected class-name before ‘{’ token
In file included from ../src/base.cc:19:
../src/../include/revwalk.h:20: error: expected class-name before ‘{’ token
Waf: Leaving directory `/Users/maarten/Downloads/nodegit/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx sig.cc -> sig_1.o}
 -> task failed (err #1): 
    {task: cxx base.cc -> base_1.o}
make: *** [build] Error 1
```

Is anyone working to get this project working with node 0.6.x? It would be great to it this out (without going back to node 0.4 :-)
