### ISSUE TITLE
Build with Electron 1.3

### ISSUE THREAD

**Issue by tensor5** [nodegit/nodegit#1089]
Electron 1.3 is based on V8 5.2.361.43, which dropped deprecated member `GetHiddenValue`.

```
export BUILD_ONLY=1
export npm_config_target=1.3.0
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_runtime=electron
export npm_config_build_from_source=true
npm install nodegit
```

```
[...]
CXX(target) Release/obj.target/nodegit/src/annotated_commit.o
../src/annotated_commit.cc: In member function ‘virtual void GitAnnotatedCommit::FromFetchheadWorker::HandleOKCallback()’:
../src/annotated_commit.cc:266:48: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
         Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                                ^~~~~~~~~~~~~~
../src/annotated_commit.cc: In member function ‘virtual void GitAnnotatedCommit::FromRefWorker::HandleOKCallback()’:
../src/annotated_commit.cc:430:48: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
         Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                                ^~~~~~~~~~~~~~
../src/annotated_commit.cc: In member function ‘virtual void GitAnnotatedCommit::FromRevspecWorker::HandleOKCallback()’:
../src/annotated_commit.cc:599:48: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
         Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
                                                ^~~~~~~~~~~~~~
../src/annotated_commit.cc: In member function ‘virtual void GitAnnotatedCommit::LookupWorker::HandleOKCallback()’:
../src/annotated_commit.cc:815:48: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
         Local<v8::Value> checkValue = nodeObj->GetHiddenValue(Nan::New("NodeGitPromiseError").ToLocalChecked());
```

**Comment by johnhaley81** [comment]
Thanks @tensor5. I'll look into this.

**Comment by maxkorp** [comment]
Wait, Electron is using v8 5.2, but the latest node is only on 5.0?

**Comment by maxkorp** [comment]
Yeah, something seems off here, I'm looking at electron/electron#master, and I'm still seeing calls to gethiddenvalue there as well. This is something we need to address, but are you sure that 1.3 si build that way?

**Comment by maxkorp** [comment]
So I've started trying to move us to get/setPrivate, but that seems to break with older versions of v8 (e.g. 5.0, as used in node 6.3)

**Comment by maxkorp** [comment]
Got a solution coming for this shortly

**Comment by maxkorp** [comment]
See #1106, soon as that lands this should be ready.
