### ISSUE TITLE
"C++20 or later required." when building with Electron 32

### ISSUE THREAD

**Issue by serggl** [nodegit/nodegit#2006]
## System information
  - node version: v20.17.0
  - yarn version: 1.22.22
  - OS/version/architecture: MacOS 15.0.1
  - Applicable nodegit version: x64

Looks like Electron 32+ will only build with C++20 and higher due to a change in v8: https://github.com/electron/electron/pull/43555

At the moment `nodegit` just does not compile with Electron `32.2.0` or `33.0.0-beta8`. The error is:

```
In file included from ../src/async_baton.cc:1:
In file included from ../src/../include/async_baton.h:7:
In file included from ../../@axosoft/nan/nan.h:62:
In file included from /Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/node.h:79:
In file included from
/Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/v8.h:23:
In file included from /Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/cppgc/common.h:8:
/Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/v8config.h:13:2: error: "C++20 or later required."
   13 | #error "C++20 or later required."
      |  ^
In file included from ../src/async_baton.cc:1:
In file included from ../src/../include/async_baton.h:7:
../../@axosoft/nan/nan.h:700:39: error: no member named 'IdleNotificationDeadline' in 'v8::Isolate'
  700 |     return v8::
Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../../@axosoft/nan/nan.h:2560:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
2560 |   tpl->SetAccessor(
      |   ~~~~~^
../../@axosoft/nan/nan.h:2608:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2608 |   tpl->SetAccessor(
      |   ~~~~~^
../../@axosoft/nan/nan.h:2654:15: error: no member named 'SetAccessor' in 'v8::Object'
 2654 |   return obj->SetAccessor
```

From what I could found, the error comes from 2 sources:
1. `nan` dependency, or actually it's fork `@axosoft/nan`. The 'no member named' problem was fixed in the original `nan` repo, so it just needs to merged into the fork: https://github.com/nodejs/nan/issues/973
2. `nodegit` scripts?  Looks like it uses C++17 to build for Electron 20 and above: https://github.com/nodegit/nodegit/blob/master/utils/defaultCxxStandard.js#L15 I guess this needs to be also adjusted for Electron 32 and above due to the mentioned change in Electron

I tried to patch for p1 by making a fork of `@axosoft/nan` and then replacing the dependency via "resolutions"entry in my package.json, but the error message is the same, though the surrounding differs and has much less details:

```
../vendor/libssh2/src/session.c:862:9: warning: variable 'packets_left' set but not used [-Wunused-but-set-variable]
  862 |     int packets_left = 0
;
      |         ^
1 warning generated.
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent_win.o
LIBTOOL-STATIC Release/ssh2.a
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/ntlm.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/unicode_builtin.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/util.o
CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/crypt_commoncrypto.o
../vendor/libgit2/deps/ntlmclient/crypt_commoncrypto.c:82:11: warning: 'CC_MD4' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
   82 |         return !!CC_MD4(in,
in_len, out);
      |                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/CommonCrypto/CommonDigest.h:115:23: note: 'CC_MD4' has been explicitly marked deprecated here
  115 | extern unsigned char
*CC_MD4(const void *data, CC_LONG len, unsigned char *md)
      |                       ^
1 warning generated.
LIBTOOL-STATIC Release/ntlmclient.a
CXX(target) Release/obj.target/nodegit/src/async_baton.o
In file included from ../src/async_baton.cc:1:
In file included from ../src/../include/async_baton.h:7:
In file included from ../../@axosoft/nan/nan.h:62
:
In file included from /Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/node.h:79:
In file included from /Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/v8.h:23:
In file included from /Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/cppgc/common.h:8:
/Users/sergeyglukhov/Library/Caches/node-gyp/32.2.0/include/node/v8config.h:13:2: error: "C++20 or later required."
   13 | #error "C++20 or later required."
      |  ^
1
error generated.
make: *** [Release/obj.target/nodegit/src/async_baton.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by serggl** [comment]
@zawata would you mind and patch the `@axosoft/nan` library as you already did this few times in the past?
Not sure who's the best person to tag for the second issue

**Comment by weedz** [comment]
Encountered this too. Changed to the latest `nan` (v2.22.0) and applied these changes to nodegit <https://github.com/weedz/nodegit/commit/7a3813a996fff9441a18e946827c27c3b68c6e0d>. Compiles on both node 22.9.0 and electron 32.2.0.

I'm not experienced in C++ so this might very well be the wrong approach but it seems to work.

**Comment by zawata** [comment]
> @zawata would you mind and patch the @axosoft/nan library as you already did this few times in the past?

We forked nan to workaround a bug that (IIRC) chromium itself is now working around. I need to double-check and do some testing but we may be able to switch back to upstream nan.

I can try to look into it this week but I've got a bunch of stuff stacked up from being out-of-town for the last week and it may be next week before I can address it.

**Comment by zawata** [comment]
Finally got time to dig into this

We switched to a custom fork of nan a while agoa because if you set an embedder field on an object, chromium had a chance to try to read the second field as a pointer and segfault:
https://github.com/Axosoft/nan/commit/d32bcab5fb077bd329208fe673def0c9cc023e03

since we encountered that issue a few years ago, chromium has attempted to work around this issue themselves:
https://chromium.googlesource.com/v8/v8/+/d41a93b0b821796afbffe5c604afee082036db58
(this commit was introduce in v8 11.3 which corresponds to node 20.1.0+)

So we're going to try switching back to upstream nan so we(I) don't have to maintain the fork anymore, but it seems like as of writing this comment, they're still trying to fix node 23/electron 33:
https://github.com/nodejs/nan/pull/979#issuecomment-2425658615

Since this seems like it will merge soon, I'm going to wait for them to merge it and publish a new version.

**Comment by ZouJiu1** [comment]
the reason is the version of node is too high, you should downgrade the version to v20

brew install node@20

v22 is too higher

**Comment by serggl** [comment]
@zawata Looks like the work on the `nan` PR you mentioned got stale...Any chance you can try to switch to the upstream `nan` without waiting for it? 🙏🏽  
Electron got bumped to v34 meanwhile and still there's a build issue with nodegit...

**Comment by serggl** [comment]
Closing this as completed via https://github.com/nodegit/nodegit/releases/tag/v0.28.0-alpha.29 
Tested with Electron v34.1.1
Many thanks to @zawata !

**Comment by zawata** [comment]
there's still an issue with building for windows and electron 34. I'm putting out a new release as soon as i can, but I've got some personal stuff to deal with todaqy and tomorrow.
