### ISSUE TITLE
Tarball cannot be downloaded from S3

### ISSUE THREAD

**Issue by strarsis** [nodegit/nodegit#834]
During nodegit installation using npm, the tarball with binaries is tried to be downloaded from amazon.
https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.2-node-v46-linux-x64.tar.gz

However, this fails with HTTP 403 (Access denied), get the URL to see the same error from amazon.
This happens with latest nodegit release.

Because of the missing binaries, npm has to rebuild it by itself.
This doesn't work when nodegit is then used:
````
Error: Cannot find module '../build/Debug/nodegit.node'
````

Using Debian Jessie amd64, node v4.0.0, npm 3.5.2.

Thank you and
with best regards

**Comment by joshaber** [comment]
Indeed, looks like binaries haven't been published for 0.6.2 yet. Could you use 0.6.1 in the mean time?

**Comment by strarsis** [comment]
Yes, I downgrade to it.

**Comment by kmalakoff** [comment]
:+1: for automating this release process since it is very time-consuming to discover there is a problem and then to revert versions.

**Comment by kmalakoff** [comment]
I've tried both reverting and rebuild from scratch over the past 3 hours, but neither are working for me.

Here's the 0.6.1 output:
```
> nodegit@0.6.1 install /PROJECT/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: /bin/sh -c /PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.1-node-v46-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/PROJECT/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/PROJECT/node_modules/nodegit/node_modules/node-pre-gyp/node_modules/request/request.js:951:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "/Users/USER/.nvm/versions/node/v4.2.2/bin/node" "/PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /PROJECT/node_modules/nodegit
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/USER/.nvm/versions/node/v4.2.2/bin/node" "/PROJECT/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /PROJECT/node_modules/nodegit/npm-debug.log
```

Here's the rebuild on 0.6.2 output:

```
  CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/des/fcrypt_b.o
  CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/ec/ecp_nistz256.o
  CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/ui/ui_compat.o
  CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/rc4/rc4_skey.o
  CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/rc4/rc4_enc.o
  LIBTOOL-STATIC Release/openssl.a
  CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
In file included from ../vendor/libssh2/src/agent.c:40:
../vendor/libssh2/src/libssh2_priv.h:44:10: fatal error: 'libssh2_config.h' file not found
#include "libssh2_config.h"
         ^
1 error generated.
make: *** [Release/obj.target/libssh2/vendor/libssh2/src/agent.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/USER/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/USER/.nvm/versions/node/v4.2.3/bin/node" "/Users/USER/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /PROJECT/node_modules/nodegit
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Comment by kmalakoff** [comment]
I found an old backup of node_modules but am now getting:

```
Uncaught Error: Module version mismatch. Expected 47, got 46.
```

I'll try reverting node and/or electron, but definitely would appreciate an easier upgrade / revert path!

**Comment by strarsis** [comment]
I had to revert to 0.6.0 (two releases back) to get it working.
````
npm install nodegit@0.6.0
````

With best regards

**Comment by kmalakoff** [comment]
@strarsis thank you. I eventually found a combination that worked, too!

**Comment by maxkorp** [comment]
0.6.2 binaries are published now for everything but windows/node5 and linux/node5, and those are actively building now.

**Comment by strarsis** [comment]
Thanks!

**Comment by maxkorp** [comment]
yeah, I've got a PR going to fix that issue right now. Unfortunately the bulids seem to not actually be going out on travis (so linux/osx). They're being built, but not deployed. Trying to sort that out right now.

**Comment by kmalakoff** [comment]
Awesome. Thank you!

I seem to be getting an error still though (see "Error: 403 status code downloading tarball" below...was there a change to the bucket permissions? this might be the problem I encountered yesterday)...

```
> nodegit@0.6.2 install /PROJECT/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: /bin/sh -c /PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.2-node-v46-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/PROJECT/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/PROJECT/node_modules/nodegit/node_modules/node-pre-gyp/node_modules/request/request.js:951:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "/Users/USER/.nvm/versions/node/v4.2.3/bin/node" "/PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /PROJECT/node_modules/nodegit
node-pre-gyp ERR! node -v v4.2.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /PROJECT/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/USER/.nvm/versions/node/v4.2.3/bin/node" "/Users/USER/.nvm/versions/node/v4.2.3/bin/npm" "install" "--ignore-scripts"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /PROJECT/node_modules/nodegit/npm-debug.log
```

**Comment by johnhaley81** [comment]
@kmalakoff can you update to 0.6.3? 0.6.2 had invalid binaries.

**Comment by kmalakoff** [comment]
@johnhaley81 Thanks! It is not released yet, but when it is, will do...

**Comment by kmalakoff** [comment]
@johnhaley81 it was released and it works. Thank you!

**Comment by johnhaley81** [comment]
@kmalakoff np :)

**Comment by morph027** [comment]
See https://github.com/nodegit/nodegit/issues/834

Got it working with ```npm install nodegit@0.6.3```

**Comment by thg303** [comment]
is this project still alive??? please if anybody got "bignum-v0.12.5-node-v59-linux-x64.tar.gz" this file upload it pleaaaseee.

**Comment by rcjsuen** [comment]
> is this project still alive??? please if anybody got this "bignum-v0.12.5-node-v59-linux-x64.tar.gz" file upload it pleaaaseee.

@thg303 What is `bignum`? This is the nodegit/nodegit project. Did you mean to post your comment in the [justmoon/node-bignum repository](https://github.com/justmoon/node-bignum)?

**Comment by thg303** [comment]
oh sorry, I lost it after 3 hours cycling between projects
